### ISSUE TITLE
[Feature Request]: Accept generic tDBConnection as source and target

### ISSUE THREAD

**Issue by bioschaf** [jlolling/talendcomp_tDBTableTransfer#3]
Newer versions of talend have generic tDB* (Input, Connection,..) components, where the user configures the vendor instead of selecting the fitting t[vendor][action] component (e.g. tOracleConnection). These generic connections can't be used with this project. Maybe it would even be possible to have a generic tDBTableTransfer that is aware of the configured DB vendors and acts accordingly.

**Comment by jlolling** [comment]
Actually the component can work with the generic connections. There is no limitation!
The generic connection components provides the Connection in exactly the same way as the old ones.

**Comment by jlolling** [comment]
[How to use generic connections](https://github.com/jlolling/talendcomp_tDBTableTransfer/blob/master/doc/using_generic_connections.png)
