### ISSUE TITLE
[Feature Request]: Option to create target table if it does not exist

### ISSUE THREAD

**Issue by bioschaf** [jlolling/talendcomp_tDBTableTransfer#6]
In some situations it would be great if the component offered the option to create the table on the target system if it does not exist (yet).
For example, to further speed up the generation of jasper reports (using tJasperReportExec), I use the tDBTableTransfer-component to transfer the data required for all the reports into an in-memory database beforehand. For this to work right now I need to create the target table(s).

**Comment by jlolling** [comment]
Such option would only be possible if we transfer complete tables not based on a query. From a query I do not get the necessary information about length and precision to be able to create the correct fields for a target table. 
I will think about the this feature in case we transfer a table and not reading a query.
